#!/bin/bash
#
# Andrew DeOrio <awdeorio@umich.edu>

# Stop on errors
set -Eeo pipefail

# Print commands
set -x

if [[ -z "$DEPLOY_ENV" ]]; then
    # run dev servers
    cd frontend
    npm run build
    cd build
    python3 -m http.server 80 &

    # run backend server
    cd ../../backend
    npx node server.js
else
    # if env variable not set, run dev servers
    # run frontend server
    cd frontend
    yarn start &
    cd ..

    cd backend
    npx nodemon server.js
fi
