#!/bin/bash
#
# Andrew DeOrio <awdeorio@umich.edu>

# Print commands
set -x

if $DEPLOY_ENV;
then
    # run production servers

    # kill existing servers
    pgrep -f python | xargs kill

    # run frontend server
    cd frontend
    npm run build
    cd build
    python3 -m http.server 80 &

    # run backend server
    cd ../../backend
    npx node server.js
else
    # if env variable not set, run dev servers
    # run frontend server
    cd frontend
    yarn start &
    cd ..

    cd backend
    npx nodemon server.js
fi
