#!/bin/bash
#
# Andrew DeOrio <awdeorio@umich.edu>

# Print commands
set -x

if [[ -z "$DEPLOY_ENV" ]];
then
    # if env variable not set, run dev servers
    # run frontend server
    cd frontend
    yarn start &
    cd ..

    cd backend
    npx nodemon server.js
else
    # run production servers

    # kill existing servers
    pgrep -f python | xargs sudo kill

    # run frontend server
    cd frontend
    cd build
    sudo python3 -m http.server 80 &

    # run backend server
    cd ../../backend
    sudo npx node server.js &
fi
